/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Categories: () => import('#controllers/admin/categories_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Home: () => import('#controllers/admin/home_controller'),
    Posts: () => import('#controllers/admin/posts_controller'),
    Session: () => import('#controllers/admin/session_controller'),
  },
}
