/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostSchema extends BaseModel {
  static $columns = [
    'categoryId',
    'content',
    'coverImage',
    'createdAt',
    'excerpt',
    'id',
    'publishedAt',
    'readTime',
    'slug',
    'status',
    'title',
    'updatedAt',
  ] as const
  $columns = PostSchema.$columns
  @column()
  declare categoryId: number | null
  @column()
  declare content: any | null
  @column()
  declare coverImage: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare excerpt: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare readTime: number
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
